"""
=============================================================================
COBOL MODERNISER — FULL PIPELINE RUNNER
=============================================================================
Purpose:
    Orchestrate the 7-agent pipeline that migrates a COBOL program to
    Python.

    Agents (in order):
        1. Parser          -- parse COBOL into structured JSON
        2. Logic Extractor -- extract business rules (makes API calls)
        3. Test Generator  -- generate comprehensive test cases BEFORE code is written
        4. Code Writer     -- produce Python from logic + structure + tests
        5. Validator       -- run ALL tests against generated code, verify to 0.01
        6. Simplifier      -- restructure code, separate business rules
        7. Externaliser    -- extract rules to YAML/JSON/Markdown

    This runner:
        - Loads each agent module dynamically
        - Feeds the output of agent N into agent N+1
        - Tracks API costs when Agent 2 uses Claude
        - Prints a tidy summary at the end

Usage:
    python demo/run_pipeline.py --input sample_cobol/mortgage.cbl
    python demo/run_pipeline.py --input sample_cobol/mortgage.cbl --no-ai
=============================================================================
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Ensure the repo root is on sys.path so ``import agents....`` works.
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# ---------------------------------------------------------------------------
# OPTIONAL COST TRACKING
# ---------------------------------------------------------------------------
try:
    from agents.cost_tracker import CostTracker, PRICING
except Exception:  # pragma: no cover
    CostTracker = None  # type: ignore[misc, assignment]
    PRICING = {}


# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

def _load_module(name: str, path: str) -> Any:
    """Load a Python module from an arbitrary file path."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot load {name} from {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def _ensure_dir(path: str) -> None:
    """Create parent directories for *path* if they do not exist."""
    Path(path).parent.mkdir(parents=True, exist_ok=True)


def _box_line(text: str, width: int = 72) -> str:
    """Centre *text* inside a box-drawing line."""
    pad = max(0, width - 2 - len(text))
    left = pad // 2
    right = pad - left
    return "\u2551" + " " * left + text + " " * right + "\u2551"


def _build_validation_report(passed, failed, total, category_results, failed_cases, test_cases):
    """Build the validation report markdown."""
    from datetime import datetime
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        "# Validation Report \u2014 Migrated Python Module",
        f"*Generated by COBOL Moderniser \u2014 Agent 5 (Validator)*",
        f"*Date: {timestamp}*",
        "",
        "---",
        "",
        f"## Verdict: {'ALL TESTS PASSED' if failed == 0 else f'{failed} TEST(S) FAILED'}",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Total test cases | {total} |",
        f"| Passed | {passed} |",
        f"| Failed | {failed} |",
        f"| Pass rate | {passed/total*100:.1f}% |" if total else "| Pass rate | N/A |",
        "| Tolerance | \u00a30.01 (to the penny) |",
        "",
        "---",
        "",
        "## Results by Category",
        "",
        "| Category | Cases | Passed | Failed | Status |",
        "|---|---|---|---|---|",
    ]

    for cat, counts in sorted(category_results.items()):
        cat_total = counts["passed"] + counts["failed"]
        cat_status = "PASS" if counts["failed"] == 0 else "FAIL"
        lines.append(f"| {cat} | {cat_total} | {counts['passed']} | {counts['failed']} | {cat_status} |")

    lines.extend(["", "---", "", "## Sample Test Results", ""])

    # Show first 3 passing cases as examples
    shown = 0
    for case in test_cases:
        if shown >= 3:
            break
        if case["id"] not in [fc["id"] for fc in failed_cases]:
            inp = case["inputs"]
            exp = case["expected"]
            lines.extend([
                f"### {case['id']} \u2014 {case.get('description', 'N/A')}",
                f"**Inputs:** \u00a3{inp['principal']:,.2f} principal, {inp['annual_rate']*100:.3f}% rate, {inp['term_years']}yr term, month {inp['repayment_month']}, {inp['rate_type']} rate",
                "",
                "| Field | Expected |",
                "|---|---|",
                f"| return_code | {exp['return_code']} |",
                f"| monthly_payment | \u00a3{exp['monthly_payment']:,.2f} |",
                f"| total_repayable | \u00a3{exp['total_repayable']:,.2f} |",
                f"| total_interest | \u00a3{exp['total_interest']:,.2f} |",
                f"| closing_balance | \u00a3{exp['closing_balance']:,.2f} |",
                f"| penalty | \u00a3{exp['penalty']:,.2f} |",
                "",
            ])
            shown += 1

    if failed > 0:
        lines.extend(["---", "", "## Failure Details", ""])
        for fc in failed_cases[:10]:
            lines.append(f"- **{fc['id']}**: {fc.get('field', fc.get('error', 'unknown error'))}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Migration Certification",
        "",
        f"The migrated Python module has **{'passed all' if failed == 0 else f'passed {passed} of'} {total} test cases**",
        f"with {failed} failure{'s' if failed != 1 else ''} across {len(category_results)} test categories.",
        "",
        "**This report was generated automatically by the COBOL Moderniser pipeline.**",
        "",
        f"*COBOL Moderniser \u2014 {timestamp}*",
        "",
    ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# AGENT STEP FUNCTIONS
# ---------------------------------------------------------------------------

def step_parser(cobol_path: str, output_json: str) -> Dict[str, Any]:
    """
    Agent 1 -- Parser.

    Parse the raw COBOL source into a structured JSON map.
    """
    print("\n" + "=" * 72)
    print("STEP 1/7 -- Parser")
    print("=" * 72)

    parser_path = _REPO_ROOT / "agents" / "parser.py"
    if not parser_path.exists():
        print("[WARN] parser.py not found -- using stub.")
        parse_data = {
            "program_id": "UNKNOWN",
            "data_fields": {},
            "paragraphs": {},
            "conditions": {},
        }
    else:
        parser = _load_module("agents.parser", str(parser_path))
        # The parser module is expected to expose a ``main()`` or
        # ``parse_cobol(source_code)`` style API.  We normalise here.
        if hasattr(parser, "parse_cobol"):
            with open(cobol_path, "r", encoding="utf-8") as fh:
                source = fh.read()
            parse_data = parser.parse_cobol(source)
        elif hasattr(parser, "main"):
            # Fallback: call main with --input and capture output file.
            import tempfile
            tmp_out = tempfile.mktemp(suffix=".json")
            old_argv = sys.argv
            try:
                sys.argv = ["parser.py", "--input", cobol_path, "--output", tmp_out]
                parser.main()
            finally:
                sys.argv = old_argv
            with open(tmp_out, "r", encoding="utf-8") as fh:
                parse_data = json.load(fh)
            os.remove(tmp_out)
        else:
            raise RuntimeError("Parser module has no parse_cobol() or main()")

    _ensure_dir(output_json)
    with open(output_json, "w", encoding="utf-8") as fh:
        json.dump(parse_data, fh, indent=2)

    print(f"[OK]  Parser output written to {output_json}")
    return parse_data


def step_logic(
    parse_data: Dict[str, Any],
    output_md: str,
    output_json: str,
    no_ai: bool = False,
    tracker: Optional[Any] = None,
) -> Dict[str, Any]:
    """
    Agent 2 -- Logic Extractor.

    Extract business rules from the parsed structure.  When *tracker* is
    supplied and AI mode is enabled, token usage is recorded automatically.
    """
    print("\n" + "=" * 72)
    print("STEP 2/7 -- Logic Extractor")
    print("=" * 72)

    extractor_path = _REPO_ROOT / "agents" / "logic_extractor.py"
    if not extractor_path.exists():
        print("[WARN] logic_extractor.py not found -- skipping.")
        return {}

    extractor = _load_module("agents.logic_extractor", str(extractor_path))

    # Run the structured extractors (no API calls).
    extracted: Dict[str, Any] = {
        "inputs": extractor.extract_inputs(parse_data),
        "outputs": extractor.extract_outputs(parse_data),
        "constants": extractor.extract_constants(parse_data),
        "validation_rules": extractor.extract_validation_rules(parse_data),
        "calculation_steps": extractor.extract_calculation_steps(parse_data),
        "conditions": extractor.extract_conditions(parse_data),
    }

    _ensure_dir(output_json)
    with open(output_json, "w", encoding="utf-8") as fh:
        json.dump(extracted, fh, indent=2)
    print(f"[OK]  Logic JSON written to {output_json}")

    # AI interpretation (optional, costs money).
    if no_ai:
        ai_text = "*AI interpretation skipped (--no-ai flag set)*"
        print("[LOGIC] Skipping AI interpretation.")
    else:
        # Pass the tracker so the extractor can record API costs.
        ai_text = extractor.interpret_with_ai(parse_data, extracted, tracker=tracker)

    # Build Markdown report.
    report = extractor.build_report(parse_data, extracted, ai_text)
    _ensure_dir(output_md)
    with open(output_md, "w", encoding="utf-8") as fh:
        fh.write(report)
    print(f"[OK]  Business rules written to {output_md}")

    return extracted


def step_codegen(
    parse_data: Dict[str, Any],
    extracted: Dict[str, Any],
    output_py: str,
) -> str:
    """
    Agent 4 -- Code Generator.

    Generate Python source from the parse tree + business logic.
    """
    print("\n" + "=" * 72)
    print("STEP 4/7 -- Code Generator")
    print("=" * 72)

    # Load the code writer (Agent 4) — tries code_writer.py first,
    # then falls back to code_generator.py for compatibility.
    codegen_path = _REPO_ROOT / "agents" / "code_writer.py"
    if not codegen_path.exists():
        codegen_path = _REPO_ROOT / "agents" / "code_generator.py"

    if codegen_path.exists():
        mod_name = "agents.code_writer" if "code_writer" in str(codegen_path) else "agents.code_generator"
        codegen = _load_module(mod_name, str(codegen_path))
        if hasattr(codegen, "generate"):
            python_code = codegen.generate(parse_data, extracted, output_py)
        else:
            python_code = _stub_codegen(parse_data, extracted)
    else:
        print("[WARN] code_writer.py not found -- using stub.")
        python_code = _stub_codegen(parse_data, extracted)

    _ensure_dir(output_py)
    with open(output_py, "w", encoding="utf-8") as fh:
        fh.write(python_code)
    print(f"[OK]  Python output written to {output_py}")
    return python_code


def step_testgen(parse_data: Dict[str, Any], output_dir: str) -> List[str]:
    """
    Agent 3 -- Test Generator.

    Generate unit tests for the migrated Python code.
    """
    print("\n" + "=" * 72)
    print("STEP 3/7 -- Test Generator")
    print("=" * 72)

    testgen_path = _REPO_ROOT / "agents" / "test_generator.py"
    if testgen_path.exists():
        testgen = _load_module("agents.test_generator", str(testgen_path))
        if hasattr(testgen, "generate_tests"):
            test_files = testgen.generate_tests(parse_data, output_dir)
        else:
            test_files = _stub_testgen(parse_data, output_dir)
    else:
        print("[WARN] test_generator.py not found -- using stub.")
        test_files = _stub_testgen(parse_data, output_dir)

    print(f"[OK]  Test files: {len(test_files)} file(s) written")
    return test_files


def step_validator(
    python_code: str,
    python_path: str,
    test_cases_path: str,
    output_dir: str,
) -> Dict[str, Any]:
    """
    Agent 5 -- Validator.

    Loads all 226 test cases, dynamically imports the generated Python
    module, runs every test case through it, and compares outputs to
    expected values with \u00a30.01 tolerance.

    Writes validation_report.md with full results.
    Returns PASS only if 100% of tests pass.
    """
    print("\n" + "=" * 72)
    print("STEP 5/7 -- Validator")
    print("=" * 72)

    # --- Load test cases ---
    if not os.path.exists(test_cases_path):
        return {
            "status": "FAIL",
            "issues": [f"Test cases not found at {test_cases_path}"],
            "passed": 0, "total": 0,
        }

    with open(test_cases_path, "r", encoding="utf-8") as fh:
        test_cases = json.load(fh)

    print(f"[VALIDATOR] Loaded {len(test_cases)} test cases from {test_cases_path}")

    # --- Dynamically import generated Python module ---
    spec = importlib.util.spec_from_file_location("generated_module", python_path)
    if spec is None or spec.loader is None:
        return {"status": "FAIL", "issues": [f"Cannot load generated module from {python_path}"], "passed": 0, "total": len(test_cases)}
    gen_mod = importlib.util.module_from_spec(spec)
    sys.modules["generated_module"] = gen_mod
    spec.loader.exec_module(gen_mod)

    if not hasattr(gen_mod, "calculate"):
        return {"status": "FAIL", "issues": ["Generated module has no calculate() function"], "passed": 0, "total": len(test_cases)}

    # --- Run all test cases ---
    from decimal import Decimal, ROUND_HALF_UP
    TOLERANCE = Decimal("0.01")
    CHECKED_FIELDS = [
        "return_code", "monthly_payment", "total_repayable", "total_interest",
        "month_interest", "month_principal", "closing_balance", "penalty",
    ]

    passed = 0
    failed = 0
    failed_cases = []
    category_results = {}

    for case in test_cases:
        inp = case["inputs"]
        expected = case["expected"]
        cat = case.get("category", "unknown")

        try:
            actual = gen_mod.calculate(
                inp["principal"], inp["annual_rate"], inp["term_years"],
                inp["repayment_month"], inp["rate_type"],
            )
        except Exception as exc:
            failed += 1
            failed_cases.append({"id": case["id"], "error": str(exc)})
            category_results.setdefault(cat, {"passed": 0, "failed": 0})["failed"] += 1
            continue

        case_passed = True
        for field in CHECKED_FIELDS:
            exp_val = expected.get(field, 0)
            act_val = getattr(actual, field, 0)

            if field == "return_code":
                match = int(exp_val) == int(act_val)
            else:
                diff = abs(Decimal(str(exp_val)) - Decimal(str(act_val)))
                match = diff <= TOLERANCE

            if not match:
                case_passed = False
                break

        if case_passed:
            passed += 1
        else:
            failed += 1
            failed_cases.append({"id": case["id"], "field": field, "expected": exp_val, "actual": act_val})

        category_results.setdefault(cat, {"passed": 0, "failed": 0})
        if case_passed:
            category_results[cat]["passed"] += 1
        else:
            category_results[cat]["failed"] += 1

    total = passed + failed
    status = "PASS" if failed == 0 else "FAIL"

    # --- Print summary ---
    print(f"[VALIDATOR] Results: {passed}/{total} passed")
    for cat, counts in sorted(category_results.items()):
        print(f"[VALIDATOR]   {cat}: {counts['passed']}/{counts['passed'] + counts['failed']} passed")
    if failed > 0:
        print(f"[VALIDATOR]   {len(failed_cases)} failures (showing first 5):")
        for fc in failed_cases[:5]:
            print(f"[VALIDATOR]     {fc['id']}: {fc.get('field', fc.get('error', 'unknown'))}")

    # --- Write validation_report.md ---
    report = _build_validation_report(passed, failed, total, category_results, failed_cases, test_cases)
    report_path = os.path.join(output_dir, "validation_report.md")
    _ensure_dir(report_path)
    with open(report_path, "w", encoding="utf-8") as fh:
        fh.write(report)
    print(f"[OK]  Validation report written to {report_path}")

    return {
        "status": status,
        "passed": passed,
        "failed": failed,
        "total": total,
        "issues": [f"{fc['id']} failed" for fc in failed_cases],
    }


def step_simplifier(input_py: str, output_py: str) -> None:
    """Agent 6 -- Simplifier."""
    print("\n" + "=" * 72)
    print("STEP 6/7 -- Simplifier")
    print("=" * 72)
    simplifier_path = _REPO_ROOT / "agents" / "simplifier.py"
    if not simplifier_path.exists():
        print("[WARN] simplifier.py not found -- skipping.")
        return
    simplifier = _load_module("agents.simplifier", str(simplifier_path))
    if hasattr(simplifier, "simplify"):
        simplifier.simplify(input_py, output_py)
    else:
        print("[WARN] simplifier.py has no simplify() function -- skipping.")
    print("[OK]  Simplifier step complete")


def step_externaliser(input_py: str, output_dir: str) -> None:
    """Agent 7 -- Externaliser."""
    print("\n" + "=" * 72)
    print("STEP 7/7 -- Externaliser")
    print("=" * 72)
    ext_path = _REPO_ROOT / "agents" / "externaliser.py"
    if not ext_path.exists():
        print("[WARN] externaliser.py not found -- skipping.")
        return
    ext = _load_module("agents.externaliser", str(ext_path))
    if hasattr(ext, "externalise"):
        ext.externalise(input_py, output_dir)
        print(f"[OK]  Business rules written to {output_dir}/business_rules.*")
    else:
        print("[WARN] externaliser.py has no externalise() function -- skipping.")


# ---------------------------------------------------------------------------
# STUBS (used when an agent module is missing)
# ---------------------------------------------------------------------------

def _stub_codegen(parse_data: Dict[str, Any], extracted: Dict[str, Any]) -> str:
    """Generate a minimal Python stub so the pipeline can still finish."""
    lines = [
        '# Generated by COBOL Moderniser (stub)',
        f'# Original: {parse_data.get("program_id", "UNKNOWN")}',
        '',
        'def main():',
        '    """TODO: implement business logic."""',
        '    pass',
        '',
        'if __name__ == "__main__":',
        '    main()',
        '',
    ]
    return "\n".join(lines)


def _stub_testgen(parse_data: Dict[str, Any], output_dir: str) -> List[str]:
    """Generate a minimal test stub so the pipeline can still finish."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "test_generated.py")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Generated tests (stub)\n")
    return [path]


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main() -> None:
    arg_parser = argparse.ArgumentParser(
        description="COBOL Moderniser -- Full 7-Agent Pipeline",
    )
    arg_parser.add_argument(
        "--input", required=True,
        help="Path to the COBOL source file (.cbl)",
    )
    arg_parser.add_argument(
        "--output-dir", default="output",
        help="Directory for all generated artefacts",
    )
    arg_parser.add_argument(
        "--no-ai", action="store_true",
        help="Skip the AI interpretation step (Agent 2) -- free mode",
    )
    arg_parser.add_argument(
        "--no-cost", action="store_true",
        help="Disable cost tracking even when AI is used",
    )
    arg_parser.add_argument(
        "--skip-simplify", action="store_true",
        help="Skip Agent 6 (Simplifier)",
    )
    args = arg_parser.parse_args()

    cobol_path = args.input
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # Cost tracker -- created once at pipeline start.
    # ------------------------------------------------------------------
    tracker: Optional[Any] = None
    if CostTracker is not None and not args.no_cost:
        tracker = CostTracker()
        print("[INFO] Cost tracking enabled.")
    else:
        print("[INFO] Cost tracking disabled.")

    overall_start = time.perf_counter()

    # ------------------------------------------------------------------
    # Step 1 -- Parser
    # ------------------------------------------------------------------
    parser_json = str(out_dir / "parser_output.json")
    parse_data = step_parser(cobol_path, parser_json)

    # ------------------------------------------------------------------
    # Step 2 -- Logic Extractor
    # ------------------------------------------------------------------
    logic_md = str(out_dir / "business_rules.md")
    logic_json = str(out_dir / "logic_output.json")
    extracted = step_logic(
        parse_data,
        logic_md,
        logic_json,
        no_ai=args.no_ai,
        tracker=tracker,
    )

    # ------------------------------------------------------------------
    # Step 3 -- Test Generator (BEFORE code is written -- test-driven)
    # Writes test cases to repo root so Step 5 always finds them.
    # ------------------------------------------------------------------
    test_dir = str(_REPO_ROOT / "tests" / "generated")
    test_files = step_testgen(parse_data, test_dir)

    # ------------------------------------------------------------------
    # Step 4 -- Code Generator (AFTER tests exist -- writes code to pass tests)
    # ------------------------------------------------------------------
    python_out = str(out_dir / "generated.py")
    python_code = step_codegen(parse_data, extracted, python_out)

    # ------------------------------------------------------------------
    # Step 5 -- Validator
    # Reads test cases from repo root (same location Step 3 writes to).
    # ------------------------------------------------------------------
    test_cases_path = str(_REPO_ROOT / "tests" / "generated" / "all_test_cases.json")
    validation = step_validator(python_code, python_out, test_cases_path, str(out_dir))

    # ------------------------------------------------------------------
    # Step 6 -- Simplifier (optional)
    # ------------------------------------------------------------------
    if not args.skip_simplify:
        simplified_py = str(out_dir / "simplified.py")
        step_simplifier(python_out, simplified_py)

    # ------------------------------------------------------------------
    # Step 7 -- Externaliser
    # ------------------------------------------------------------------
    step_externaliser(python_out, str(out_dir))

    overall_elapsed = time.perf_counter() - overall_start

    # ------------------------------------------------------------------
    # Cost report (before final summary so it appears above the box).
    # ------------------------------------------------------------------
    if tracker is not None and tracker.has_records:
        tracker.print_summary()
        cost_report_path = str(out_dir / "cost_report.json")
        tracker.save(cost_report_path)
        print(f"[OK]  Cost report saved to {cost_report_path}")

    # ------------------------------------------------------------------
    # Final summary box
    # ------------------------------------------------------------------
    print("\n\u2554" + "\u2550" * 74 + "\u2557")
    print("\u2551               COBOL MODERNISER \u2014 PIPELINE COMPLETE                           \u2551")
    print("\u2560" + "\u2550" * 74 + "\u2563")

    status_text = "PASS" if validation["status"] == "PASS" else "FAIL"
    status_colour_tag = ""  # terminals that support it can add ANSI codes
    print(f"\u2551   Status        : {status_text:<58} \u2551")
    print(f"\u2551   Input         : {cobol_path:<58} \u2551")
    print(f"\u2551   Output dir    : {str(out_dir):<58} \u2551")
    print(f"\u2551   Duration      : {overall_elapsed:.1f}s{'':<54} \u2551")
    print(f"\u2551   Pipeline      : 7-Agent Pipeline{'':<35} \u2551")
    print("\u2551\u2500" + "\u2500" * 73 + "\u2562")

    # Cost line (only when applicable)
    if tracker is not None and tracker.has_records:
        cost = tracker.total_cost_usd
        tokens = tracker.total_tokens
        cost_line = f"API cost:  ${cost:.4f}  |  {tokens:,} tokens"
        print(f"\u2551   {cost_line:<69} \u2551")
    elif args.no_ai:
        print(f"\u2551   API cost:  $0.0000  |  0 tokens ( --no-ai mode ){'':<17} \u2551")
    elif CostTracker is None:
        print(f"\u2551   API cost:  n/a  (cost_tracker module unavailable){'':<19} \u2551")

    print("\u2551\u2500" + "\u2500" * 73 + "\u2562")
    print(f"\u2551   Business rules: {logic_md:<58} \u2551")
    passed = validation.get("passed", 0)
    total = validation.get("total", 0)
    print(f"\u2551   Validation    : {passed}/{total} tests passed{'':<33} \u2551")
    print("\u255a" + "\u2550" * 74 + "\u255d\n")


if __name__ == "__main__":
    main()

